/* audiotest -- does the AICA actually play anything under Flycast?
 *
 * kb/design-audio.md ends on a question this program exists to answer: the
 * game's music stream prefills four callbacks and then never gets asked for
 * another byte.  snd_stream_poll() decides that by reading the play position
 * out of SPU RAM at AICA_MEM_CHANNELS -- a structure the *ARM* firmware
 * writes, not a hardware register.  So a frozen callback count has two very
 * different causes:
 *
 *   a) the ARM core is not executing KOS's driver at all (nothing in SPU RAM
 *      ever changes), or
 *   b) the ARM is alive but the stream channels are not advancing.
 *
 * This program has no game, no GL and no shim in it.  It brings up the stream
 * driver, feeds it a generated square wave, and prints the three numbers that
 * separate those cases:
 *
 *   clk   AICA_MEM_CLOCK -- a millisecond counter the ARM firmware bumps.
 *         Frozen => (a): the ARM is not running.  This is the load-bearing one.
 *   qh/qt SH4->AICA command queue head/tail.  The SH-4 writes head, the ARM
 *         moves tail as it consumes.  tail < head forever => (a) as well.
 *   pos   the play position of stream channel 0, the exact expression
 *         snd_stream_poll() branches on (snd_stream.c:805).
 *
 * plus cb, the number of times our get_data callback ran.  Four means prefill
 * only, which is the game's symptom reproduced without the game.
 */

#include <kos.h>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>

#include <dc/scif.h>
#include <dc/g2bus.h>
#include <dc/spu.h>
#include <dc/sound/sound.h>
#include <dc/sound/stream.h>
#include <dc/sound/aica_comm.h>
#include <arch/timer.h>

#include "fiqprobe.h"   /* generated by mkfiqprobe.py; see fiqprobe.s */

/* Emulator-only baud; see harness/dc/README.md. Never call scif_flush(). */
#define HARNESS_BAUD 1562500

/* From kernel/arch/dreamcast/sound/arm/aica_cmd_iface.h, which KOS does not
 * install into $KOS_BASE/include. Kept in sync by hand; the values are part of
 * the SH-4/ARM ABI and have not changed since KOS 1.x. */
#define AICA_MEM_CMD_QUEUE  0x010000
#define AICA_MEM_CHANNELS   0x020000
#define AICA_MEM_CLOCK      0x021000
#define AICA_CHANNEL(x)     (AICA_MEM_CHANNELS + (x) * sizeof(aica_channel_t))

/* AICA register file, same macro hardware/spu.c uses. */
#define SNDREGADDR(x)       (0xa0700000 + (x))
#define CHNREG(ch, x)       SNDREGADDR(0x80 * (ch) + (x))

#define SND_RATE      22050
#define SND_CHANNELS  2
#define BUFSIZE       (16 * 1024)   /* same as dc/src/dc_mixer.c */
#define RUN_MS        10000
#define POLL_MS       20

static snd_stream_hnd_t stream = SND_STREAM_INVALID;
static int16_t         *pcm;            /* interleaved stereo scratch */
static volatile int     cb_count = 0;
static uint32_t         phase = 0;

/* A 440 Hz square wave, generated on demand. Square rather than sine so that
 * if a human ever listens to this, silence is unmistakable. */
static void *get_data(snd_stream_hnd_t hnd, int req_bytes, int *recv_bytes) {
    int frames, i;

    (void)hnd;

    if(req_bytes > BUFSIZE)
        req_bytes = BUFSIZE;

    frames = req_bytes / (2 * SND_CHANNELS);

    for(i = 0; i < frames; i++) {
        /* 22050 / 440 ~= 50 frames per cycle, 25 high, 25 low. */
        int16_t s = ((phase % 50) < 25) ? 8000 : -8000;
        pcm[i * 2 + 0] = s;
        pcm[i * 2 + 1] = s;
        phase++;
    }

    cb_count++;
    *recv_bytes = frames * 2 * SND_CHANNELS;
    return pcm;
}

static uint32_t spu_rd(uint32_t off) {
    return g2_read_32(SPU_RAM_UNCACHED_BASE + off);
}

/* MEASURED (fiqprobe, this file): Flycast's ARM7 ignores `msr CPSR_c, rN` --
 * the byte-field form -- so the I and F bits never change. `msr CPSR, rN`
 * (full field) works. KOS's arm_fiq_enable() (sound/arm/crt0.s) uses the
 * byte-field form, so the FIQ mask stays set, no timer interrupt is ever
 * taken, AICA_MEM_CLOCK never moves, and arm_main() hangs forever in
 * timer_wait() -- which is exactly the silence this file was written to chase.
 *
 * KOS ships the firmware prebuilt (no ARM compiler in the SDK image), so the
 * fix is a two-word patch applied to SPU RAM between snd_init() and the ARM
 * being let out of reset:
 *
 *   e121f000  msr cpsr_c, r0   ->   e12ff000  msr cpsr_fsxc, r0
 *
 * The value written is whatever mrs just produced with only I/F edited, so
 * widening the field mask changes nothing on real hardware.
 */
#define ARM_MRS_R0      0xe10f0000u   /* mrs r0, cpsr        */
#define ARM_ORR_R0_80   0xe3800080u   /* orr r0, r0, #0x80   */
#define ARM_BIC_R0_40   0xe3c00040u   /* bic r0, r0, #0x40   */
#define ARM_MSR_CPSR_C  0xe121f000u   /* msr cpsr_c, r0      */
#define ARM_MSR_CPSR_A  0xe12ff000u   /* msr cpsr_fsxc, r0   */
#define ARM_NOP         0xe1a00000u   /* mov r0, r0          */

static int patch_kos_fiq(void) {
    const uint32_t fw_size = 3344;   /* KOS's stream.drv, exactly */
    static uint32_t fw[3344 / 4];
    uint32_t i;
    int patched = 0;

    spu_disable();

    /* Read the firmware back, patch it in main RAM, and write the whole block
     * again with spu_memload(). Patching individual words in place with
     * g2_write_32() was measured to have no effect on what the ARM executes:
     * the words read back changed, the behaviour did not. A block reload is
     * also the same path snd_init() itself uses. */
    spu_memread(fw, 0, fw_size);

    for(i = 0; i + 3 < fw_size / 4; i++) {
        if(fw[i] == ARM_MRS_R0 && fw[i + 1] == ARM_ORR_R0_80 &&
           fw[i + 2] == ARM_BIC_R0_40 && fw[i + 3] == ARM_MSR_CPSR_C) {
            fw[i + 1] = ARM_NOP;            /* leave the I bit alone     */
            fw[i + 3] = ARM_MSR_CPSR_A;     /* full-field msr            */
            patched++;
        }
        /* timer_wait() -> heartbeat at 0x21018 + return, so the SH-4 can see
         * whether arm_main()'s loop is running at all. */
        if(fw[i] == 0xe3a03a21u && fw[i + 1] == 0xe1a02003u &&
           fw[i + 2] == 0xe5933000u && fw[i + 3] == 0xe0830000u) {
            fw[i + 1] = 0xe2833018u;   /* add r3,r3,#0x18 */
            fw[i + 2] = 0xe5930000u;   /* ldr r0,[r3]     */
            fw[i + 3] = 0xe2800001u;   /* add r0,r0,#1    */
            fw[i + 4] = 0xe5830000u;   /* str r0,[r3]     */
            fw[i + 5] = 0xe1a0f00eu;   /* mov pc, lr      */
            patched += 10;
        }
        /* arm_main(): skip the aica_init() call and the aica_get_pos() call
         * in the loop, to bisect where the ARM stops. */
        if(fw[i] == 0xe583200cu && fw[i + 2] == 0xe3a05a21u) {
            fw[i + 1] = ARM_NOP;
            patched += 100;
        }
        if(fw[i] == 0xe1a00004u && fw[i + 1] == 0xe2844001u &&
           fw[i + 3] == 0xe3540040u) {
            fw[i + 2] = ARM_NOP;
            patched += 1000;
        }
    }

    spu_memload(0, fw, fw_size);

    spu_enable();
    thd_sleep(50);
    return patched;
}

/* aica_get_pos() from the SH-4 side: select the channel to observe in the
 * low byte of 0x280c, wait, then read the position out of 0x2814. */
static uint32_t aica_pos(int ch) {
    int i;
    g2_write_8(SNDREGADDR(0x280d), (uint8_t)ch);
    for(i = 0; i < 20; i++)
        __asm__ volatile ("nop");
    return g2_read_32(SNDREGADDR(0x2814)) & 0xffff;
}

static uint32_t chan_pos(int ch) {
    return spu_rd(AICA_CHANNEL(ch) + offsetof(aica_channel_t, pos)) & 0xffff;
}

int main(int argc, char **argv) {
    uint64_t t0, now, next_report;
    uint32_t clk_first, clk_last, pos_first;
    int      clk_moved = 0, pos_moved = 0, cb_after_prefill;
    int      prefill_cb;

    (void)argc; (void)argv;

    scif_set_parameters(HARNESS_BAUD, 1);
    scif_init();
    dbgio_dev_select("scif");

    printf("TR-DC-HARNESS-BEGIN\n");
    printf("MARK:BOOT_OK\n");

    pcm = memalign(32, BUFSIZE);
    if(pcm == NULL) {
        printf("ASSERT fail alloc_pcm\n");
        printf("TR-DC-HARNESS-END rc=1\n");
        return 1;
    }

    /* snd_stream_init_ex() implicitly calls snd_init(), which is what uploads
     * the ARM firmware into SPU RAM and releases the core from reset. */
    if(snd_stream_init_ex(SND_CHANNELS, BUFSIZE) < 0) {
        printf("ASSERT fail snd_stream_init_ex\n");
        printf("TR-DC-HARNESS-END rc=1\n");
        return 1;
    }
    printf("ASSERT ok snd_stream_init_ex\n");
    printf("MEM aica_free=%d\n", (int)snd_mem_available());

    /* Did the firmware upload land at all? snd_init() writes it with
     * spu_memload_sq(), i.e. through the store queues; if Flycast drops SQ
     * writes aimed at G2 space, SPU RAM is still zero here and the ARM is
     * executing nothing. Offset 0 is the ARM reset vector, never 0x00000000. */
    printf("MARK:FW %08lx %08lx %08lx %08lx\n",
           (unsigned long)spu_rd(0x00), (unsigned long)spu_rd(0x04),
           (unsigned long)spu_rd(0x08), (unsigned long)spu_rd(0x0c));
    printf("MARK:QUEUE valid=%lu process_ok=%lu size=%lu data=%08lx\n",
           (unsigned long)spu_rd(AICA_MEM_CMD_QUEUE + offsetof(aica_queue_t, valid)),
           (unsigned long)spu_rd(AICA_MEM_CMD_QUEUE + offsetof(aica_queue_t, process_ok)),
           (unsigned long)spu_rd(AICA_MEM_CMD_QUEUE + offsetof(aica_queue_t, size)),
           (unsigned long)spu_rd(AICA_MEM_CMD_QUEUE + offsetof(aica_queue_t, data)));

    /* Is the ARM out of reset? spu_enable() clears bit 0 of the AICA register
     * at 0xa0702c00 (hardware/spu.c:291). If the read-back still has bit 0
     * set, the write is not reaching the AICA and no firmware will ever run. */
    printf("MARK:ARMRST after_init=%08lx\n",
           (unsigned long)g2_read_32(SNDREGADDR(0x2c00)));
    {
        int sites = patch_kos_fiq();
        printf("MARK:FIQPATCH probe_loop=%lu sites=%d fw=%08lx/%08lx/%08lx/%08lx qvalid=%lu\n",
               (unsigned long)spu_rd(0x21004), sites,
               (unsigned long)spu_rd(0xa8), (unsigned long)spu_rd(0xac),
               (unsigned long)spu_rd(0xb0), (unsigned long)spu_rd(0xb4),
               (unsigned long)spu_rd(AICA_MEM_CMD_QUEUE +
                                     offsetof(aica_queue_t, valid)));
    }
    thd_sleep(200);
    printf("MARK:ARMRST after_enable=%08lx clk=%lu\n",
           (unsigned long)g2_read_32(SNDREGADDR(0x2c00)),
           (unsigned long)spu_rd(AICA_MEM_CLOCK));

    /* KOS's ARM firmware only advances AICA_MEM_CLOCK from its FIQ handler,
     * and arm_main()'s loop ends in timer_wait(10) (sound/arm/main.c:224),
     * which spins until that clock moves. So no FIQ => the firmware hangs on
     * its first iteration, exactly like a dead ARM. These are the registers
     * that decide whether the FIQ can happen at all, sampled twice:
     *
     *   TIMA  0x2890  timer A: counter in the low byte, /4410 prescale
     *   SCIEB 0x289c  interrupt enable; aica_init() sets bit 6 (timer A)
     *   SCIPD 0x28a0  interrupt pending
     *   SCILV 0x28a8/ac/b0  the 3-bit level the ARM reads back as INTREQ
     *   INTREQ 0x2d00 what the FIQ handler ANDs with 7 (crt0.s: 2 == timer)
     */
    {
        uint32_t a_tima = g2_read_32(SNDREGADDR(0x2890));
        uint32_t a_pd   = g2_read_32(SNDREGADDR(0x28a0));
        uint32_t a_req  = g2_read_32(SNDREGADDR(0x2d00));
        thd_sleep(500);
        printf("MARK:AICAREG tima=%08lx->%08lx scieb=%08lx scipd=%08lx->%08lx "
               "scilv=%08lx/%08lx/%08lx intreq=%08lx->%08lx\n",
               (unsigned long)a_tima, (unsigned long)g2_read_32(SNDREGADDR(0x2890)),
               (unsigned long)g2_read_32(SNDREGADDR(0x289c)),
               (unsigned long)a_pd,   (unsigned long)g2_read_32(SNDREGADDR(0x28a0)),
               (unsigned long)g2_read_32(SNDREGADDR(0x28a8)),
               (unsigned long)g2_read_32(SNDREGADDR(0x28ac)),
               (unsigned long)g2_read_32(SNDREGADDR(0x28b0)),
               (unsigned long)a_req,  (unsigned long)g2_read_32(SNDREGADDR(0x2d00)));
    }

    /* The ARM has had 10 ms inside snd_init() to start. Sample the clock
     * before anything else touches the queue. */
    clk_first = spu_rd(AICA_MEM_CLOCK);
    printf("MARK:CLOCK_FIRST %lu\n", (unsigned long)clk_first);

    stream = snd_stream_alloc(get_data, BUFSIZE);
    if(stream == SND_STREAM_INVALID) {
        printf("ASSERT fail snd_stream_alloc\n");
        printf("TR-DC-HARNESS-END rc=1\n");
        return 1;
    }
    printf("ASSERT ok snd_stream_alloc\n");

    snd_stream_start(stream, SND_RATE, SND_CHANNELS == 2);
    snd_stream_volume(stream, 255);
    prefill_cb = cb_count;
    pos_first  = chan_pos(0);
    printf("MARK:STARTED cb=%d pos=%lu\n", prefill_cb, (unsigned long)pos_first);

    t0 = timer_ms_gettime64();
    next_report = t0;
    clk_last = clk_first;

    for(;;) {
        uint32_t clk, qh, qt, p0, p1;

        now = timer_ms_gettime64();
        if(now - t0 >= RUN_MS)
            break;

        snd_stream_poll(stream);

        if(now >= next_report) {
            clk = spu_rd(AICA_MEM_CLOCK);
            qh  = spu_rd(AICA_MEM_CMD_QUEUE + offsetof(aica_queue_t, head));
            qt  = spu_rd(AICA_MEM_CMD_QUEUE + offsetof(aica_queue_t, tail));
            p0  = chan_pos(0);
            p1  = chan_pos(1);

            if(clk != clk_first) clk_moved = 1;
            if(p0  != pos_first) pos_moved = 1;
            clk_last = clk;

            printf("PERF t=%lu clk=%lu hb=%lu qh=%lu qt=%lu ok=%lu pos0=%lu pos1=%lu cb=%d\n",
                   (unsigned long)(now - t0), (unsigned long)clk,
                   (unsigned long)spu_rd(0x21018),
                   (unsigned long)qh, (unsigned long)qt,
                   (unsigned long)spu_rd(AICA_MEM_CMD_QUEUE + offsetof(aica_queue_t, process_ok)),
                   (unsigned long)p0, (unsigned long)p1, cb_count);
            next_report = now + 500;
        }

        thd_sleep(POLL_MS);
    }

    cb_after_prefill = cb_count - prefill_cb;

    /* The three questions, in the order they have to be answered. */
    printf("ASSERT %s arm_clock_advances\n", clk_moved ? "ok" : "fail");
    printf("ASSERT %s stream_pos_advances\n", pos_moved ? "ok" : "fail");
    printf("ASSERT %s callbacks_after_prefill\n",
           cb_after_prefill > 0 ? "ok" : "fail");
    printf("PERF clk_delta=%lu cb_total=%d cb_after_prefill=%d\n",
           (unsigned long)(clk_last - clk_first), cb_count, cb_after_prefill);

    snd_stream_stop(stream);
    snd_stream_destroy(stream);
    snd_stream_shutdown();

    /* Phase 2: drive an AICA channel from the SH-4, with no ARM firmware in
     * the path at all.
     *
     * Everything above establishes that KOS's ARM driver never gets going
     * under Flycast. But the ARM is only a proxy: the channel registers live
     * in the AICA register file, which the SH-4 can reach directly over G2 at
     * 0xa0700000. This programs channel 0 exactly the way sound/arm/aica.c
     * does and then reads the play position back the same way aica_get_pos()
     * does -- if that position advances, an SH-4-side mixer is viable and the
     * ARM can be left out of the design entirely.
     */
    {
        const int    ch     = 0;
        const int    nsamp  = 4410;          /* 0.2 s at 22050 Hz */
        const uint32_t rate = 22050;
        uint32_t aram, freq_lo, freq_base = 5644800;
        int      freq_hi = 7, i;
        uint32_t p_a, p_b, p_c;
        int16_t *tone;

        aram = snd_mem_malloc(nsamp * 2);
        tone = memalign(32, nsamp * 2);

        if(aram != 0 && tone != NULL) {
            for(i = 0; i < nsamp; i++)
                tone[i] = ((i % 50) < 25) ? 8000 : -8000;   /* 441 Hz square */

            spu_memload(aram, tone, nsamp * 2);

            /* Master volume + mono/stereo, as aica_init() sets it. */
            g2_write_32(SNDREGADDR(0x2800), 0x000f);

            g2_write_32(CHNREG(ch, 0), 0x8000);             /* key off       */
            g2_write_32(CHNREG(ch, 8), 0);                  /* loop start    */
            g2_write_32(CHNREG(ch, 12), nsamp & 0xffff);    /* loop end      */

            while(rate < freq_base && freq_hi > -8) {
                freq_base >>= 1;
                --freq_hi;
            }
            freq_lo = (rate << 10) / freq_base;
            g2_write_32(CHNREG(ch, 24), (freq_hi << 11) | (freq_lo & 1023));

            g2_write_8(CHNREG(ch, 36), 0);                  /* pan centre    */
            g2_write_8(CHNREG(ch, 37), 0xf);                /* DISDL max     */
            g2_write_8(CHNREG(ch, 40), 0x24);               /* LPF off       */
            g2_write_8(CHNREG(ch, 41), 0);                  /* vol: 0 == max */
            g2_write_32(CHNREG(ch, 16), 0x1f);              /* no envelope   */

            g2_write_32(CHNREG(ch, 4), aram & 0xffff);
            /* mode 0 == 16-bit PCM; 0x0200 == loop forever; 0xc000 == key on */
            g2_write_32(CHNREG(ch, 0),
                        0xc000 | 0x0200 | ((aram >> 16) & 0x7f));

            p_a = aica_pos(ch);
            thd_sleep(200);
            p_b = aica_pos(ch);
            thd_sleep(200);
            p_c = aica_pos(ch);

            printf("PERF aram=%08lx pos_a=%lu pos_b=%lu pos_c=%lu\n",
                   (unsigned long)aram, (unsigned long)p_a,
                   (unsigned long)p_b, (unsigned long)p_c);
            printf("ASSERT %s aica_channel_plays\n",
                   (p_b != p_a || p_c != p_b) ? "ok" : "fail");

            g2_write_32(CHNREG(ch, 0), 0x8000);             /* key off       */
        }
        else {
            printf("ASSERT fail aica_direct_alloc\n");
        }
    }

    printf("TR-DC-HARNESS-END rc=0\n");
    return 0;
}
