#!/usr/bin/env python3
"""Assemble fiqprobe.s for the AICA ARM7 and emit fiqprobe.h.

Run by build.sh. The SDK image has no ARM compiler -- KOS ships its sound
firmware prebuilt -- but the host's clang can assemble armv4t, so the probe is
assembled here and the raw .text bytes are inlined into the SH-4 program as a
C array. There is no objcopy on this host either, so .text is carved out of the
ELF by parsing the section header table (32-bit little-endian ARM ELF).
"""

import struct
import subprocess
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "fiqprobe.s")
OBJ = os.path.join(HERE, "fiqprobe.o")
HDR = os.path.join(HERE, "fiqprobe.h")


def text_section(path):
    with open(path, "rb") as f:
        elf = f.read()
    assert elf[:4] == b"\x7fELF" and elf[4] == 1, "expected a 32-bit ELF"
    e_shoff, = struct.unpack_from("<I", elf, 0x20)
    e_shentsize, e_shnum, e_shstrndx = struct.unpack_from("<HHH", elf, 0x2e)
    def sh(i):
        off = e_shoff + i * e_shentsize
        (name, typ, flags, addr, offset, size) = struct.unpack_from("<IIIIII", elf, off)
        return name, typ, offset, size
    strtab_off = sh(e_shstrndx)[2]
    for i in range(e_shnum):
        name, typ, offset, size = sh(i)
        end = elf.index(b"\0", strtab_off + name)
        if elf[strtab_off + name:end] == b".text":
            return elf[offset:offset + size]
    raise SystemExit("no .text section in " + path)


def main():
    cc = os.environ.get("TR_ARM_AS", "clang")
    subprocess.run([cc, "-target", "armv4t-none-eabi", "-c", SRC, "-o", OBJ],
                   check=True)
    blob = text_section(OBJ)
    os.remove(OBJ)

    words = len(blob) // 4
    assert len(blob) % 4 == 0, "ARM .text is not a whole number of words"

    with open(HDR, "w") as f:
        f.write("/* Generated by mkfiqprobe.py from fiqprobe.s -- do not edit. */\n")
        f.write("#ifndef FIQPROBE_H\n#define FIQPROBE_H\n\n")
        f.write("#define FIQPROBE_WORDS %d\n\n" % words)
        f.write("static const uint32_t fiqprobe[FIQPROBE_WORDS] = {\n")
        for i in range(0, words, 4):
            row = struct.unpack_from("<" + "I" * min(4, words - i), blob, i * 4)
            f.write("    " + " ".join("0x%08xu," % w for w in row) + "\n")
        f.write("};\n\n#endif\n")
    print("fiqprobe.h: %d bytes of ARM code" % len(blob))


if __name__ == "__main__":
    main()
